name: Build and test C++ library
on: [push, workflow_dispatch]

jobs:
  build_and_test:
    name: ${{ github.workflow } on ${{ matrix.os }}-
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx

    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10.1

      - name: Create a build directory
        run: mkdir build

      - name: Configure cmake
        run: > 
          cmake -B build -S . 
          -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"
      
      - name: Build with cmake
        run: cmake --build build --config Release

      - name: Test
        run: ctest --test-dir build