name: Build release

on: 
  push:
    tags:
      - "v*.*.*"

jobs:
  build_wheels:
    name: Python wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Clone vcpkg
        run: git submodule update --init --recursive ./vcpkg
        
      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10.1

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          # vcpkg does not support i686 nor aarch64
          CIBW_ARCHS_LINUX: "x86_64"
          # Skip musllinux builds
          CIBW_SKIP: "*-musllinux_*"
          # Pre install vcpkg (needed for macOS)
          CIBW_BEFORE_BUILD_MACOS: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh; ${{ github.workspace }}/vcpkg/vcpkg install
          CIBW_BEFORE_BUILD_WINDOWS: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.bat; ${{ github.workspace }}/vcpkg/vcpkg install

      - name: Upload python wheels
        uses: actions/upload-artifact@v2
        with:
          name: python-wheels
          path: ./wheelhouse/*.whl
  
  # TODO build python sdist

  # TODO build C++ library
    
  release:
    name: Make a Release
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download python wheels
        uses: actions/download-artifact@v3
        with:
          name: python-wheels
          path: ./wheelhouse/
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./wheelhouse/*