name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macOS-10.15]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
        
      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10.1


      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl